project_id = "nqdndkwtxbbgovfzemcn"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.get-maps-key]
verify_jwt = false

[functions.manage-user-role]
verify_jwt = false

[functions.lookup-profile]
verify_jwt = false

[functions.import-drivers-csv]
verify_jwt = false

[functions.import-users]
verify_jwt = false

[functions.import-vehicles]
verify_jwt = false

[functions.trigger-sos]
verify_jwt = false

[functions.auto-expire-trips]
verify_jwt = false

[functions.import-passengers-csv]
verify_jwt = false

[functions.notify-topup-request]
verify_jwt = false

[functions.notify-new-driver]
verify_jwt = false

[functions.notify-vehicle-update]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
